### ISSUE TITLE
[BUG] com.karuslabs:satisfactory 1.1.3 is not available

### ISSUE THREAD

**Issue by josejulio** [Pante/elementary#237]
**Describe the bug**
While trying to import the project, I noticed that the version 1.1.3 of `satisfactory` is not available

**To Reproduce**
1. Navigate to: https://repo.karuslabs.com/#browse/browse:elementary-releases:com%2Fkaruslabs%2Fsatisfactory
2. Confirm that the last version is 1.1.2

**Expected behavior**
I was expecting to see the last version of satisfactory to be aligned with all the other version given that this version is found on the [README](https://github.com/Pante/elementary).

**Screenshots**

![image](https://github.com/Pante/elementary/assets/3845764/ef3cd649-89bd-4a56-ae6f-db30e3da75ec)

**Environment (please complete the following information):**
 - Java Version 17

**Additional context**
N/A

**Comment by Pante** [comment]
Ah it’s a typo, the latest version for satisfactory is 1.1.2. I’m not going to release a new version since 2.0.0 is long overdue, haven’t had the time to release it recently.
