### ISSUE TITLE
Documentation examples require Utilitary.

### ISSUE THREAD

**Issue by garretwilson** [Pante/elementary#295]
The [examples in the documentation](https://github.com/Pante/elementary/blob/master/docs/elementary/tour.md) seem to assume that Utilitary is being included as a dependency (e.g. `com.karuslabs.utilitary.type.TypeMirrors` is imported), but nothing in the documentation indicates that I should have added `com.karuslabs:utilitary` as a dependency. I'm left wondering why the code copied from the documentation doesn't compile, and then I have to do Maven searches to find out where to get those classes.

The documentation should be updated to indicate that Utilitary is required.

```xml
<dependency>
  <groupId>com.karuslabs</groupId>
  <artifactId>utilitary</artifactId>
  <version>2.0.0</version>
  <scope>test</scope>
</dependency>
```

**Comment by Pante** [comment]
Thanks for the report, this definitely should be happening since we do shade `Utilitary`.
