### ISSUE TITLE
Missing page "Why java 11?"

### ISSUE THREAD

**Issue by hohserg1** [Pante/elementary#38]
Follow link exists at wiki:
https://github.com/Pante/elementary/wiki/faqwhy-does-elementary-require-java-11-and-above
![image](https://user-images.githubusercontent.com/35610168/129809356-4230ad71-d5c5-48bd-913f-18584087d93f.png)
But related page is not exists.
How about to write it?

**Comment by Pante** [comment]
Thanks for catching this issue, it seems like I forgot to remove the link when copying it from my other repository that I used as a template.

**Comment by Pante** [comment]
Add the page, thanks for pointing it out! 😄

**Comment by hohserg1** [comment]
Link at Home page still invalid

**Comment by Pante** [comment]
whoops, forget to save the changes, fixed now!
